### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by dkipping** [openHPI/jenz#2]
DASHBOARD Ideensammlung
 

Weltkarte­ als Kugel
- Dreht sich
- Bei klick geht auf zu landkarte, rein zoomen etc
- Sieht user die gerade online sind
- Über den Tag online waren
- Verlauf über den Tag wer online war
- Vertelung der User (wo lernen sie)

Kurse → https://open.hpi.de/feeds/courses
- Aktuelle & upcoming
- genauer anschauen -> details (wenn auf Kurs geklickt)
- Fragen ob kurs beitreten
- Email
- QR-Code…
- Video abspielen wenn Ton möglich?

Statistiken (gesamt)
- Filtern der Statistiken etc. welche Plattform (OpenSap,…)
- So viele neue Anmeldungen/Einschreibungen (wie bei Facebook, neue Likes-Statistik)
- Wie viele Kurse abgeschlossen wurden
- Populärste Kurse
- Course activity -> forum posts…

Geschichte von OpenHpi zum durchscrollen
- Desktop – Mobile (Entwicklung)
- Zeitstrahl mit Ereignissen zum draufklicken
- (Wandel design)

Eventfeed
- Neue Einschreibung  -> Benachrichtigung
- Twitter-Feed

Meinungen von Usern

Sonstiges:
- Stichworte – Facts
- Eventuell auch FunFacts
- Sprachauswahl
- Interactive - wie zu zeigen?

Angular, React, Polymer - Vor-/Nachteile
 
Anwendung sollte nicht abstürzen

**Comment by flowirtz** [comment]
moved [here](https://github.com/openHPI/jenz/wiki/Initial-Brainstorming-Ideas) as this is no issue.
